# Generated by Django 3.1 on 2020-09-18 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.CharField(choices=[('Linkedin', 'Linkedin'), ('Pole-Emploi', 'Pôle-Emploi')], max_length=255, verbose_name='Site')),
                ('subject', models.CharField(help_text='Nom du Post', max_length=255, verbose_name='Sujet')),
                ('link_search', models.CharField(max_length=255, unique=True, verbose_name='Lien')),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.CharField(max_length=255, null=True, unique=True, verbose_name='Site')),
                ('not_read', models.IntegerField(default=0, verbose_name='Non lue')),
                ('applied', models.IntegerField(default=0, verbose_name='Postulé')),
                ('inadequate', models.IntegerField(default=0, verbose_name='Inadéquate')),
                ('expired', models.IntegerField(default=0, verbose_name='Expiré')),
                ('other', models.IntegerField(default=0, verbose_name='Autres')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255, verbose_name='Localisation')),
                ('link', models.CharField(max_length=255, unique=True, verbose_name='Lien')),
                ('status', models.CharField(choices=[('not-read', 'Non Lu'), ('applied', 'Postulé'), ('inadequate', 'Inadéquate'), ('expired', 'Expiré'), ('other', 'Autres')], max_length=255)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.search')),
            ],
        ),
    ]
