# Generated by Django 3.1 on 2020-09-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web', models.CharField(max_length=255, unique=True, verbose_name='Site')),
                ('not_read', models.IntegerField(default=0, verbose_name='Non lue')),
                ('applied', models.IntegerField(default=0, verbose_name='Postulé')),
                ('inadequate', models.IntegerField(default=0, verbose_name='Inadéquate')),
                ('expired', models.IntegerField(default=0, verbose_name='Expiré')),
                ('other', models.IntegerField(default=0, verbose_name='Autres')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
            ],
        ),
        migrations.AlterField(
            model_name='search',
            name='web',
            field=models.CharField(choices=[('Linkedin', 'Linkedin'), ('Pole-Emploi', 'Pôle-Emploi')], max_length=255, verbose_name='Site'),
        ),
    ]
