# Generated by Django 3.1 on 2020-10-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200921_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.search', unique=True),
        ),
    ]
